spring:
  application:
    name: "food-service"
  datasource:
    url: jdbc:mysql://localhost:3306/food-service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9092