spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/rishabvashisth7/configuration-microservices.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
   
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9096

encrypt:
  key: "ndjsndkdwowjnrnkenofeo033n3k4n5nkkq110ndnr"
