server:
  port: 9098

info:
  app:
    name: "Food Service---> after new changes"
    description: "This is new changed--> bus refeshed Food Service production. Ready to serve users."
    version: "2.0==>Production-->newwet" 